version: '3.8'

services:
  quobuz:
    image: chwps/quobuz:latest
    container_name: quobuz
    ports:
      - "3420:3420"
    volumes:
      - ./quobuz_data:/app/quobuz_data
      - ./Music/Qobuz:/app/Music/Qobuz
    env_file:
      - .env
    restart: unless-stopped
